services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backend_hub_xp/data/mongo:/data/db
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:

      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./backend_hub_xp/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
