org: menossijose
app: lambdatest
service: lambda

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGODB_URI: http://localhost:4566
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  salesReport:
    handler: sales-handler.generateSalesReport
    events:
      - httpApi:
          path: /sales-report
          method: post
    environment:
      NODE_OPTIONS: --enable-source-maps
    timeout: 30
